version: '3'

services:
  selenium:
    network_mode: host
    image: selenium/standalone-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"

  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: "TRUE"
    ports:
      - "4040:4040"
      - "5050:5050"
    volumes:
      - 'allure:/app/allure-results'
      - './allure-report:/allure-report'

  tests:
    network_mode: host
    build: .
    image: 'imhio_autotests'
    volumes:
      - './front:/autotests/front'  # TODO: move to dev compose file
      - 'allure:/allure'
    command: "bash"  # cd front && pytest
    depends_on:
      - selenium

volumes:
  allure:
